from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from models import Book, Author, Genre

if __name__ == "__main__":
    engine = create_engine("sqlite:///book.db")
    Session = sessionmaker(bind=engine)
    session = Session()

    # Delete existing records before any insertion
    session.query(Book).delete()
    session.query(Author).delete()
    session.query(Genre).delete()

    # Create instances for each class
    books = [
        Book(
            title="The Great Gatsby",
            isbn=9780743273565,
            publication_date="1925-04-10",
            description="Classic novel about the American Dream",
            publisher="Scribner",
            language="English",
            pages_count=180,
            rating=4,
        ),
        Book(
            title="To Kill a Mockingbird",
            isbn=9780061120084,
            publication_date="1960-07-11",
            description="Powerful story on racial injustice",
            publisher="Harper Perennial Modern Classics",
            language="English",
            pages_count=281,
            rating=5,
        ),
        Book(
            title="1984",
            isbn=9780451524935,
            publication_date="1949-06-08",
            description="Dystopian vision of a totalitarian future",
            publisher="Signet Classics",
            language="English",
            pages_count=328,
            rating=4,
        ),
        Book(
            title="Pride and Prejudice",
            isbn=9780141439518,
            publication_date="1813-01-28",
            description="Classic romance novel",
            publisher="Penguin Classics",
            language="English",
            pages_count=279,
            rating=4,
        ),
        Book(
            title="The Catcher in the Rye",
            isbn=9780316769488,
            publication_date="1951-07-16",
            description="Coming-of-age novel",
            publisher="Back Bay Books",
            language="English",
            pages_count=224,
            rating=3,
        ),
        Book(
            title="Pride and Prejudice",
            isbn=9780141439518,
            publication_date="1813-01-28",
            description="A classic novel about love and social status in 19th century England",
            publisher="Penguin Classics",
            language="English",
            pages_count=480,
            rating=4,
        ),
        Book(
            title="Jane Eyre",
            isbn=9780141441146,
            publication_date="1847-10-16",
            description="A novel about the struggles and triumphs of a young orphan girl",
            publisher="Penguin Classics",
            language="English",
            pages_count=624,
            rating=4,
        ),
        Book(
            title="Wuthering Heights",
            isbn=9780141439556,
            publication_date="1847-12-19",
            description="A tale of love, revenge, and the supernatural on the Yorkshire moors",
            publisher="Penguin Classics",
            language="English",
            pages_count=416,
            rating=4,
        ),
        Book(
            title="The Picture of Dorian Gray",
            isbn=9780141439570,
            publication_date="1890-07-01",
            description="A novel about the corruption of the soul and the pursuit of eternal youth",
            publisher="Penguin Classics",
            language="English",
            pages_count=304,
            rating=4,
        ),
        Book(
            title="Crime and Punishment",
            isbn=9780143058144,
            publication_date="1866-11-14",
            description="A psychological thriller about guilt, redemption, and the human condition",
            publisher="Penguin Classics",
            language="English",
            pages_count=671,
            rating=4,
        ),
        Book(
            title="Anna Karenina",
            isbn=9780143035008,
            publication_date="1877-01-28",
            description="A tragic love story set in the Russian aristocracy",
            publisher="Penguin Classics",
            language="English",
            pages_count=864,
            rating=4,
        ),
        Book(
            title="One Hundred Years of Solitude",
            isbn=9780060883287,
            publication_date="1967-05-30",
            description="A multi-generational epic of the Buendía family in the fictional town of Macondo",
            publisher="Harper Perennial Modern Classics",
            language="English",
            pages_count=417,
            rating=4,
        ),
        Book(
            title="The Great Gatsby",
            isbn=9780743273565,
            publication_date="1925-04-10",
            description="A novel about the American Dream, wealth, and the Jazz Age",
            publisher="Scribner",
            language="English",
            pages_count=180,
            rating=4,
        ),
        Book(
            title="The Sun Also Rises",
            isbn=9780743297332,
            publication_date="1926-10-22",
            description='A novel about the "Lost Generation" after World War I',
            publisher="Scribner",
            language="English",
            pages_count=251,
            rating=4,
        ),
        Book(
            title="To Kill a Mockingbird",
            isbn=9780061120085,
            publication_date="1960-07-11",
            description="A novel about racial injustice and moral growth",
            publisher="Harper Perennial Modern Classics",
            language="English",
            pages_count=281,
            rating=4,
        ),
        Book(
            title="1984",
            isbn=9780451524935,
            publication_date="1949-06-08",
            description="Dystopian novel about totalitarianism and surveillance",
            publisher="Signet Classics",
            language="English",
            pages_count=328,
            rating=5,
        ),
        Book(
            title="Brave New World",
            isbn=9780060850524,
            publication_date="1932-10-19",
            description="A novel about a dystopian society based on mass production and consumerism",
            publisher="Harper Perennial Modern Classics",
            language="English",
            pages_count=288,
            rating=4,
        ),
        Book(
            title="The Catcher in the Rye",
            isbn=9780316769488,
            publication_date="1951-07-16",
            description="A novel about adolescent alienation and rebellion",
            publisher="Back Bay Books",
            language="English",
            pages_count=277,
            rating=4,
        ),
        Book(
            title="Lord of the Flies",
            isbn=9780399501487,
            publication_date="1954-09-17",
            description="A novel about the collapse of society and the savagery of human nature",
            publisher="Penguin Books",
            language="English",
            pages_count=224,
            rating=4,
        ),
        Book(
            title="Animal Farm",
            isbn=9780451526342,
            publication_date="1945-08-17",
            description="A political allegory about the Russian Revolution and totalitarianism",
            publisher="Signet Classics",
            language="English",
            pages_count=141,
            rating=4,
        ),
        Book(
            title="Fahrenheit 451",
            isbn=9781451673319,
            publication_date="1953-10-19",
            description="A novel about censorship and the suppression of free thought",
            publisher="Simon & Schuster",
            language="English",
            pages_count=249,
            rating=4,
        ),
        Book(
            title="The Grapes of Wrath",
            isbn=9780143039433,
            publication_date="1939-04-14",
            description="Novel about the struggles of a family during the Great Depression",
            publisher="Penguin Classics",
            language="English",
            pages_count=464,
            rating=4,
        ),
        Book(
            title="Moby-Dick",
            isbn=9780142437247,
            publication_date="1851-10-18",
            description="Adventure novel about a whaling voyage",
            publisher="Penguin Classics",
            language="English",
            pages_count=720,
            rating=4,
        ),
        Book(
            title="The Catcher in the Rye",
            isbn=9780316769488,
            publication_date="1951-07-16",
            description="A coming-of-age novel about teenage angst and disillusionment",
            publisher="Back Bay Books",
            language="English",
            pages_count=234,
            rating=4,
        ),
        Book(
            title="To Kill a Mockingbird",
            isbn=9780060935467,
            publication_date="1960-07-11",
            description="A novel about racial injustice and the loss of innocence in the American South",
            publisher="Harper Perennial Modern Classics",
            language="English",
            pages_count=336,
            rating=4,
        ),
        Book(
            title="The Lord of the Rings",
            isbn=9780544003415,
            publication_date="1954-07-29",
            description="An epic high fantasy novel about the quest to destroy the One Ring",
            publisher="Mariner Books",
            language="English",
            pages_count=1178,
            rating=4,
        ),
        Book(
            title="The Hobbit",
            isbn=9780547928227,
            publication_date="1937-09-21",
            description="A children's fantasy novel about a hobbit's adventure to reclaim treasure",
            publisher="Mariner Books",
            language="English",
            pages_count=300,
            rating=4,
        ),
        Book(
            title="The Adventures of Huckleberry Finn",
            isbn=9780143107323,
            publication_date="1884-12-10",
            description="A novel about the adventures of a young boy and a runaway slave on the Mississippi River",
            publisher="Penguin Classics",
            language="English",
            pages_count=400,
            rating=4,
        ),
        Book(
            title="The Scarlet Letter",
            isbn=9780142437261,
            publication_date="1850-03-16",
            description="A novel about adultery and redemption in colonial New England",
            publisher="Penguin Classics",
            language="English",
            pages_count=276,
            rating=4,
        ),
        Book(
            title="Heart of Darkness",
            isbn=9780141441672,
            publication_date="1899-02-01",
            description="A novella about the journey up the Congo River in search of the enigmatic Kurtz",
            publisher="Penguin Classics",
            language="English",
            pages_count=96,
            rating=4,
        ),
        Book(
            title="The Canterbury Tales",
            isbn=9780140424386,
            publication_date="1387-01-01",
            description="A collection of stories told by pilgrims on their way to Canterbury",
            publisher="Penguin Classics",
            language="English",
            pages_count=528,
            rating=4,
        ),
        Book(
            title="Don Quixote",
            isbn=9780060934347,
            publication_date="1605-01-16",
            description="A novel about a delusional knight and his loyal squire",
            publisher="Harper Perennial Modern Classics",
            language="English",
            pages_count=992,
            rating=4,
        ),
        Book(
            title="Les Misérables",
            isbn=9780140444308,
            publication_date="1862-04-03",
            description="A novel about the struggles of ex-convict Jean Valjean and the Parisian poor",
            publisher="Penguin Classics",
            language="English",
            pages_count=1463,
            rating=4,
        ),
        Book(
            title="The Brothers Karamazov",
            isbn=9780374528379,
            publication_date="1880-11-26",
            description="A novel about family, faith, and morality",
            publisher="Farrar, Straus and Giroux",
            language="English",
            pages_count=796,
            rating=4,
        ),
        Book(
            title="The Stranger",
            isbn=9780679720201,
            publication_date="1942-01-01",
            description="A novel exploring existentialism and absurdity",
            publisher="Vintage International",
            language="English",
            pages_count=123,
            rating=4,
        ),
        Book(
            title="Slaughterhouse-Five",
            isbn=9780385333849,
            publication_date="1969-03-31",
            description="A satirical novel on the horrors of war",
            publisher="Delta Publishing",
            language="English",
            pages_count=275,
            rating=4,
        ),
        Book(
            title="The Hitchhiker's Guide to the Galaxy",
            isbn=9780345391803,
            publication_date="1979-10-12",
            description="A humorous science fiction novel",
            publisher="Del Rey Books",
            language="English",
            pages_count=216,
            rating=4,
        ),
        Book(
            title="The Bell Jar",
            isbn=9780060837020,
            publication_date="1963-01-14",
            description="A semi-autobiographical novel on mental health",
            publisher="Harper Perennial Modern Classics",
            language="English",
            pages_count=244,
            rating=4,
        ),
        Book(
            title="The Road",
            isbn=9780307387899,
            publication_date="2006-09-26",
            description="A post-apocalyptic novel about survival and hope",
            publisher="Vintage Books",
            language="English",
            pages_count=287,
            rating=4,
        ),
        Book(
            title="Catch-22",
            isbn=9780684833392,
            publication_date="1961-11-10",
            description="A satirical war novel",
            publisher="Simon & Schuster",
            language="English",
            pages_count=453,
            rating=4,
        ),
        Book(
            title="The Grapes of Wrath",
            isbn=9780670016907,
            publication_date="1939-04-14",
            description="A novel about social injustice and human resilience",
            publisher="Viking Press",
            language="English",
            pages_count=464,
            rating=4,
        ),
        Book(
            title="Middlemarch",
            isbn=9780141439543,
            publication_date="1871-12-01",
            description="A novel about provincial life and societal changes",
            publisher="Penguin Classics",
            language="English",
            pages_count=904,
            rating=4,
        ),
        Book(
            title="A Clockwork Orange",
            isbn=9780393312836,
            publication_date="1962-09-12",
            description="A dystopian novel on free will and societal control",
            publisher="W. W. Norton & Company",
            language="English",
            pages_count=213,
            rating=4,
        ),
        Book(
            title="The Brothers Karamazov",
            isbn=9780374528379,
            publication_date="1880-11-26",
            description="A novel about family, faith, and morality",
            publisher="Farrar, Straus and Giroux",
            language="English",
            pages_count=796,
            rating=4,
        ),
        Book(
            title="The Stranger",
            isbn=9780679720201,
            publication_date="1942-01-01",
            description="A novel exploring existentialism and absurdity",
            publisher="Vintage International",
            language="English",
            pages_count=123,
            rating=4,
        ),
        Book(
            title="Slaughterhouse-Five",
            isbn=9780385333849,
            publication_date="1969-03-31",
            description="A satirical novel on the horrors of war",
            publisher="Delta Publishing",
            language="English",
            pages_count=275,
            rating=4,
        ),
        Book(
            title="The Hitchhiker's Guide to the Galaxy",
            isbn=9780345391803,
            publication_date="1979-10-12",
            description="A humorous science fiction novel",
            publisher="Del Rey Books",
            language="English",
            pages_count=216,
            rating=4,
        ),
        Book(
            title="The Bell Jar",
            isbn=9780060837020,
            publication_date="1963-01-14",
            description="A semi-autobiographical novel on mental health",
            publisher="Harper Perennial Modern Classics",
            language="English",
            pages_count=244,
            rating=4,
        ),
        Book(
            title="The Road",
            isbn=9780307387899,
            publication_date="2006-09-26",
            description="A post-apocalyptic novel about survival and hope",
            publisher="Vintage Books",
            language="English",
            pages_count=287,
            rating=4,
        ),
        Book(
            title="Catch-22",
            isbn=9780684833392,
            publication_date="1961-11-10",
            description="A satirical war novel",
            publisher="Simon & Schuster",
            language="English",
            pages_count=453,
            rating=4,
        ),
        Book(
            title="Middlemarch",
            isbn=9780141439543,
            publication_date="1871-12-01",
            description="A novel about provincial life and societal changes",
            publisher="Penguin Classics",
            language="English",
            pages_count=904,
            rating=4,
        ),
        Book(
            title="A Clockwork Orange",
            isbn=9780393312836,
            publication_date="1962-09-12",
            description="A dystopian novel on free will and societal control",
            publisher="W. W. Norton & Company",
            language="English",
            pages_count=213,
            rating=4,
        ),
        Book(
            title="Norwegian Wood",
            isbn=9780375704024,
            publication_date="1987-09-01",
            description="A nostalgic novel about love and loss",
            publisher="Vintage Books",
            language="English",
            pages_count=296,
            rating=4,
        ),
        Book(
            title="The Fountainhead",
            isbn=9780451191151,
            publication_date="1943-05-07",
            description="A novel about individualism and integrity",
            publisher="Signet Book",
            language="English",
            pages_count=752,
            rating=4,
        ),
        Book(
            title="Watership Down",
            isbn=9780743273565,
            publication_date="1972-11-02",
            description="An epic fantasy about a group of rabbits",
            publisher="Scribner",
            language="English",
            pages_count=478,
            rating=4,
        ),
        Book(
            title="A Farewell to Arms",
            isbn=9780684801469,
            publication_date="1929-09-27",
            description="A novel set during World War I",
            publisher="Scribner",
            language="English",
            pages_count=332,
            rating=4,
        ),
        Book(
            title="The Count of Monte Cristo",
            isbn=9780140449266,
            publication_date="1844-08-28",
            description="An adventure novel about revenge and justice",
            publisher="Penguin Classics",
            language="English",
            pages_count=1276,
            rating=4,
        ),
        Book(
            title="A Tale of Two Cities",
            isbn=9780141439604,
            publication_date="1859-11-26",
            description="A historical novel set in London and Paris before and during the French Revolution",
            publisher="Penguin Classics",
            language="English",
            pages_count=489,
            rating=4,
        ),
        Book(
            title="The Idiot",
            isbn=9780679642427,
            publication_date="1869-01-26",
            description="A novel about a naive and compassionate prince",
            publisher="Everyman's Library",
            language="English",
            pages_count=656,
            rating=4,
        ),
        Book(
            title="The Name of the Wind",
            isbn=9780756404741,
            publication_date="2007-03-27",
            description="A fantasy novel about a legendary figure named Kvothe",
            publisher="DAW Books",
            language="English",
            pages_count=662,
            rating=4,
        ),
        Book(
            title="The Master and Margarita",
            isbn=9780679760801,
            publication_date="1967-11-06",
            description="A satirical novel with elements of fantasy and political commentary",
            publisher="Vintage Books",
            language="English",
            pages_count=402,
            rating=4,
        ),
        Book(
            title="Wuthering Heights",
            isbn=9780141439556,
            publication_date="1847-12-19",
            description="A tale of love, revenge, and the supernatural on the Yorkshire moors",
            publisher="Penguin Classics",
            language="English",
            pages_count=416,
            rating=4,
        ),
        Book(
            title="The Alchemist",
            isbn=9780062315007,
            publication_date="1988-01-01",
            description="A story about following dreams and destiny",
            publisher="HarperOne",
            language="English",
            pages_count=208,
            rating=5,
        ),
        Book(
            title="The Name of the Wind",
            isbn=9780756404741,
            publication_date="2007-03-27",
            description="An epic fantasy of a gifted young magician",
            publisher="DAW Books",
            language="English",
            pages_count=662,
            rating=4,
        ),
        Book(
            title="The Picture of Dorian Gray",
            isbn=9780141439570,
            publication_date="1890-07-01",
            description="A novel about the corruption of the soul and the pursuit of eternal youth",
            publisher="Penguin Classics",
            language="English",
            pages_count=304,
            rating=4,
        ),
        Book(
            title="The Handmaid's Tale",
            isbn=9780385490818,
            publication_date="1985-09-17",
            description="A dystopian novel about a totalitarian society",
            publisher="Anchor Books",
            language="English",
            pages_count=311,
            rating=4,
        ),
        Book(
            title="The Silmarillion",
            isbn=9780345325815,
            publication_date="1977-09-15",
            description="A collection of mythopoeic stories",
            publisher="Del Rey Books",
            language="English",
            pages_count=365,
            rating=4,
        ),
        Book(
            title="The Shining",
            isbn=9780307743657,
            publication_date="1977-01-28",
            description="A psychological horror novel",
            publisher="Anchor Books",
            language="English",
            pages_count=447,
            rating=4,
        ),
        Book(
            title="The Martian",
            isbn=9780553418026,
            publication_date="2014-02-11",
            description="Science fiction survival novel on Mars",
            publisher="Broadway Books",
            language="English",
            pages_count=369,
            rating=4,
        ),
        Book(
            title="The Godfather",
            isbn=9780451205766,
            publication_date="1969-03-10",
            description="Crime novel about the Mafia",
            publisher="Signet Book",
            language="English",
            pages_count=448,
            rating=4,
        ),
        Book(
            title="Frankenstein",
            isbn=9780486282114,
            publication_date="1818-01-01",
            description="Gothic novel about a scientist and his creation",
            publisher="Dover Publications",
            language="English",
            pages_count=166,
            rating=4,
        ),
        Book(
            title="Dracula",
            isbn=9780486411095,
            publication_date="1897-05-26",
            description="Classic horror novel about Count Dracula",
            publisher="Dover Publications",
            language="English",
            pages_count=418,
            rating=4,
        ),
        Book(
            title="The Hitchhiker's Guide to the Galaxy",
            isbn=9780345391803,
            publication_date="1979-10-12",
            description="A humorous science fiction novel",
            publisher="Del Rey Books",
            language="English",
            pages_count=216,
            rating=4,
        ),
        Book(
            title="The Metamorphosis",
            isbn=9780553213690,
            publication_date="1915-10-15",
            description="A novella about a man transforming into an insect",
            publisher="Bantam Classics",
            language="English",
            pages_count=201,
            rating=4,
        ),
        Book(
            title="The Odyssey",
            isbn=9780140268867,
            publication_date="800 BC",
            description="Epic poem about Odysseus' journey home",
            publisher="Penguin Classics",
            language="English",
            pages_count=541,
            rating=4,
        ),
        Book(
            title="The Road to Wigan Pier",
            isbn=9780141185293,
            publication_date="1937-03-08",
            description="A sociopolitical critique of poverty and social injustice",
            publisher="Penguin Classics",
            language="English",
            pages_count=240,
            rating=4,
        ),
        Book(
            title="The Wind-Up Bird Chronicle",
            isbn=9780679775430,
            publication_date="1994-05-01",
            description="A surreal and enigmatic narrative exploring human consciousness",
            publisher="Vintage Books",
            language="English",
            pages_count=607,
            rating=4,
        ),
        Book(
            title="Infinite Jest",
            isbn=9780316066525,
            publication_date="1996-02-01",
            description="A complex and sprawling novel exploring addiction and entertainment",
            publisher="Back Bay Books",
            language="English",
            pages_count=1104,
            rating=4,
        ),
        Book(
            title="The Book Thief",
            isbn=9780375842207,
            publication_date="2005-03-14",
            description="A novel narrated by Death during World War II",
            publisher="Alfred A. Knopf",
            language="English",
            pages_count=552,
            rating=4,
        ),
        Book(
            title="The Catcher in the Rye",
            isbn=9780316769488,
            publication_date="1951-07-16",
            description="A coming-of-age novel about teenage angst and disillusionment",
            publisher="Back Bay Books",
            language="English",
            pages_count=277,
            rating=4,
        ),
        Book(
            title="The Power of Now",
            isbn=9781577314806,
            publication_date="1997-09-29",
            description="A spiritual guide to living in the present moment",
            publisher="New World Library",
            language="English",
            pages_count=236,
            rating=4,
        ),
        Book(
            title="East of Eden",
            isbn=9780140186390,
            publication_date="1952-09-19",
            description="A multigenerational family saga set in California",
            publisher="Penguin Books",
            language="English",
            pages_count=601,
            rating=4,
        ),
        Book(
            title="The Stand",
            isbn=9780307743688,
            publication_date="1978-09-01",
            description="A post-apocalyptic horror novel",
            publisher="Anchor Books",
            language="English",
            pages_count=1153,
            rating=4,
        ),
        Book(
            title="American Gods",
            isbn=9780062059888,
            publication_date="2001-06-19",
            description="A fantasy novel about gods and mythological creatures in modern America",
            publisher="William Morrow",
            language="English",
            pages_count=635,
            rating=4,
        ),
        Book(
            title="A Thousand Splendid Suns",
            isbn=9781594483851,
            publication_date="2007-05-22",
            description="A story of friendship and resilience in Afghanistan",
            publisher="Riverhead Books",
            language="English",
            pages_count=432,
            rating=4,
        ),
        Book(
            title="The Handmaid's Tale",
            isbn=9780385490818,
            publication_date="1985-09-17",
            description="A dystopian novel about a totalitarian society",
            publisher="Anchor Books",
            language="English",
            pages_count=311,
            rating=4,
        ),
        Book(
            title="The Silmarillion",
            isbn=9780345325815,
            publication_date="1977-09-15",
            description="A collection of mythopoeic stories",
            publisher="Del Rey Books",
            language="English",
            pages_count=365,
            rating=4,
        ),
        Book(
            title="The Shining",
            isbn=9780307743657,
            publication_date="1977-01-28",
            description="A psychological horror novel",
            publisher="Anchor Books",
            language="English",
            pages_count=447,
            rating=4,
        ),
        Book(
            title="The Martian",
            isbn=9780553418026,
            publication_date="2014-02-11",
            description="Science fiction survival novel on Mars",
            publisher="Broadway Books",
            language="English",
            pages_count=369,
            rating=4,
        ),
        Book(
            title="The Godfather",
            isbn=9780451205766,
            publication_date="1969-03-10",
            description="Crime novel about the Mafia",
            publisher="Signet Book",
            language="English",
            pages_count=448,
            rating=4,
        ),
        Book(
            title="Frankenstein",
            isbn=9780486282114,
            publication_date="1818-01-01",
            description="Gothic novel about a scientist and his creation",
            publisher="Dover Publications",
            language="English",
            pages_count=166,
            rating=4,
        ),
        Book(
            title="Dracula",
            isbn=9780486411095,
            publication_date="1897-05-26",
            description="Classic horror novel about Count Dracula",
            publisher="Dover Publications",
            language="English",
            pages_count=418,
            rating=4,
        ),
        Book(
            title="Nineteen Eighty-Four",
            isbn=9780451524935,
            publication_date="1949-06-08",
            description="Dystopian vision of a totalitarian future",
            publisher="Signet Classics",
            language="English",
            pages_count=328,
            rating=4,
        ),
        Book(
            title="The Picture of Dorian Gray",
            isbn=9780141439570,
            publication_date="1890-07-01",
            description="A novel about the corruption of the soul and the pursuit of eternal youth",
            publisher="Penguin Classics",
            language="English",
            pages_count=304,
            rating=4,
        ),
        Book(
            title="Norwegian Wood",
            isbn=9780375704024,
            publication_date="1987-09-01",
            description="A nostalgic novel about love and loss",
            publisher="Vintage Books",
            language="English",
            pages_count=296,
            rating=4,
        ),
        Book(
            title="The Handmaid's Tale",
            isbn=9780385490818,
            publication_date="1985-09-17",
            description="A dystopian novel about a totalitarian society",
            publisher="Anchor Books",
            language="English",
            pages_count=311,
            rating=4,
        ),
        Book(
            title="The Road",
            isbn=9780307387899,
            publication_date="2006-09-26",
            description="A post-apocalyptic novel about survival and hope",
            publisher="Vintage Books",
            language="English",
            pages_count=287,
            rating=4,
        ),
        Book(
            title="To the Lighthouse",
            isbn=9780156907392,
            publication_date="1927-05-05",
            description="A novel exploring the complexity of human relationships",
            publisher="Harcourt Brace & Company",
            language="English",
            pages_count=209,
            rating=4,
        ),
        Book(
            title="The Stranger",
            isbn=9780679720201,
            publication_date="1942-01-01",
            description="A novel exploring existentialism and absurdity",
            publisher="Vintage International",
            language="English",
            pages_count=123,
            rating=4,
        ),
        Book(
            title="Slaughterhouse-Five",
            isbn=9780385333849,
            publication_date="1969-03-31",
            description="A satirical novel on the horrors of war",
            publisher="Delta Publishing",
            language="English",
            pages_count=275,
            rating=4,
        ),
        Book(
            title="The Hitchhiker's Guide to the Galaxy",
            isbn=9780345391803,
            publication_date="1979-10-12",
            description="A humorous science fiction novel",
            publisher="Del Rey Books",
            language="English",
            pages_count=216,
            rating=4,
        ),
        Book(
            title="The Bell Jar",
            isbn=9780060837020,
            publication_date="1963-01-14",
            description="A semi-autobiographical novel on mental health",
            publisher="Harper Perennial Modern Classics",
            language="English",
            pages_count=244,
            rating=4,
        ),
        Book(
            title="Catch-22",
            isbn=9780684833392,
            publication_date="1961-11-10",
            description="A satirical war novel",
            publisher="Simon & Schuster",
            language="English",
            pages_count=453,
            rating=4,
        ),
        Book(
            title="The Grapes of Wrath",
            isbn=9780670016907,
            publication_date="1939-04-14",
            description="A novel about social injustice and human resilience",
            publisher="Viking Press",
            language="English",
            pages_count=464,
            rating=4,
        ),
        Book(
            title="Middlemarch",
            isbn=9780141439543,
            publication_date="1871-12-01",
            description="A novel about provincial life and societal changes",
            publisher="Penguin Classics",
            language="English",
            pages_count=904,
            rating=4,
        ),
        Book(
            title="A Clockwork Orange",
            isbn=9780393312836,
            publication_date="1962-09-12",
            description="A dystopian novel on free will and societal control",
            publisher="W. W. Norton & Company",
            language="English",
            pages_count=213,
            rating=4,
        ),
        Book(
            title="Beloved",
            isbn=9781400033416,
            publication_date="1987-09-02",
            description="A story of slavery and its aftermath",
            publisher="Vintage Books",
            language="English",
            pages_count=324,
            rating=4,
        ),
        Book(
            title="Moby-Dick",
            isbn=9780142437247,
            publication_date="1851-10-18",
            description="Adventure novel about a whaling voyage",
            publisher="Penguin Classics",
            language="English",
            pages_count=720,
            rating=4,
        ),
        Book(
            title="The Grapes of Wrath",
            isbn=9780143039433,
            publication_date="1939-04-14",
            description="Novel about the struggles of a family during the Great Depression",
            publisher="Penguin Classics",
            language="English",
            pages_count=464,
            rating=4,
        ),
    ]

    authors = [
        Author(name="Margaret Atwood", best_seller="The Testaments"),
        Author(name="Harper Lee", best_seller="Go Set a Watchman"),
        Author(name="Agatha Christie", best_seller="And Then There Were None"),
        Author(name="F. Scott Fitzgerald", best_seller="The Great Gatsby"),
        Author(name="J.D. Salinger", best_seller="Franny and Zooey"),
        Author(name="Charles Dickens", best_seller="Great Expectations"),
        Author(name="Leo Tolstoy", best_seller="Anna Karenina"),
        Author(name="Gabriel Garcia Marquez", best_seller="The Autumn of the Patriarch"),
        Author(name="Virginia Woolf", best_seller="Mrs. Dalloway"),
        Author(name="Kazuo Ishiguro", best_seller="The Buried Giant"),
        Author(name="George Orwell", best_seller="Animal Farm"),
        Author(name="Albert Camus", best_seller="The Stranger"),
        Author(name="Ernest Hemingway", best_seller="For Whom the Bell Tolls"),
        Author(name="Toni Morrison", best_seller="Sula"),
        Author(name="Mark Twain", best_seller="The Adventures of Tom Sawyer"),
        Author(name="Fyodor Dostoevsky", best_seller="The Brothers Karamazov"),
        Author(name="Chinua Achebe", best_seller="Things Fall Apart"),
        Author(name="James Joyce", best_seller="Dubliners"),
        Author(name="Dante Alighieri", best_seller="The Divine Comedy"),
        Author(name="T.S. Eliot", best_seller="The Waste Land"),
        Author(name="George R.R. Martin", best_seller="A Game of Thrones"),
        Author(name="Herman Melville", best_seller="Moby-Dick"),
        Author(name="Miguel de Cervantes", best_seller="Don Quixote"),
        Author(name="Mary Shelley", best_seller="Frankenstein"),
        Author(name="Emily Bronte", best_seller="Wuthering Heights"),
        Author(name="H.G. Wells", best_seller="The War of the Worlds"),
        Author(name="Victor Hugo", best_seller="Les Misérables"),
        Author(name="Franz Kafka", best_seller="The Metamorphosis"),
        Author(name="John Milton", best_seller="Paradise Lost"),
        Author(name="Anne Frank", best_seller="The Diary of a Young Girl"),
        Author(name="Jules Verne", best_seller="Twenty Thousand Leagues Under the Sea"),
        Author(name="Anton Chekhov", best_seller="The Cherry Orchard"),
        Author(name="Homer", best_seller="The Iliad and The Odyssey"),
        Author(name="Arthur Conan Doyle", best_seller="The Hound of the Baskervilles"),
        Author(name="Sylvia Plath", best_seller="The Bell Jar"),
        Author(name="John Keats", best_seller="Ode to a Nightingale"),
        Author(name="Gabriel Garcia Marquez", best_seller="In Evil Hour"),
        Author(name="Henry James", best_seller="The Turn of the Screw"),
        Author(name="Edgar Allan Poe", best_seller="The Raven and Other Poems"),
        Author(name="Ralph Ellison", best_seller="Invisible Man"),
        Author(name="Bram Stoker", best_seller="Dracula"),
        Author(name="Lewis Carroll", best_seller="Alice’s Adventures in Wonderland"),
        Author(name="Oscar Wilde", best_seller="The Importance of Being Earnest"),
        Author(name="Daphne du Maurier", best_seller="Jamaica Inn"),
        Author(name="William Faulkner", best_seller="The Sound and the Fury"),
        Author(name="Hermann Hesse", best_seller="Siddhartha"),
        Author(name="Virginia Woolf", best_seller="Orlando"),
        Author(name="Ernest Hemingway", best_seller="A Farewell to Arms"),
        Author(name="Jane Austen", best_seller="Sense and Sensibility"),
        Author(name="George Eliot", best_seller="Middlemarch"),
        Author(name="Walt Whitman", best_seller="Leaves of Grass"),
        Author(name="Dostoevsky", best_seller="Notes from Underground"),
        Author(name="Franz Kafka", best_seller="The Trial"),
        Author(name="Emily Dickinson", best_seller="Complete Poems"),
        Author(name="Rudyard Kipling", best_seller="The Jungle Book"),
        Author(name="George Bernard Shaw", best_seller="Pygmalion"),
        Author(name="Jack London", best_seller="The Call of the Wild"),
        Author(name="Robert Louis Stevenson", best_seller="Treasure Island"),
        Author(name="Johann Wolfgang von Goethe", best_seller="Faust"),
        Author(name="Charlotte Bronte", best_seller="Jane Eyre"),
        Author(name="H.P. Lovecraft", best_seller="The Call of Cthulhu"),
        Author(name="Thomas Hardy", best_seller="Tess of the d'Urbervilles"),
        Author(name="Graham Greene", best_seller="The Quiet American"),
        Author(name="Wilkie Collins", best_seller="The Woman in White"),
        Author(name="Edgar Rice Burroughs", best_seller="Tarzan of the Apes"),
        Author(name="Daphne du Maurier", best_seller="My Cousin Rachel"),
        Author(name="Charles Dickens", best_seller="David Copperfield"),
        Author(name="Kurt Vonnegut", best_seller="Slaughterhouse-Five"),
        Author(name="Aldous Huxley", best_seller="Island"),
        Author(name="E.M. Forster", best_seller="A Passage to India"),
        Author(name="Samuel Beckett", best_seller="Waiting for Godot"),
        Author(name="John Updike", best_seller="Rabbit, Run"),
        Author(name="John Milton", best_seller="Paradise Lost"),
        Author(name="G.K. Chesterton", best_seller="The Man Who Was Thursday"),
        Author(name="John Green", best_seller="The Fault in Our Stars"),
        Author(name="William Wordsworth", best_seller="Lyrical Ballads"),
        Author(name="Voltaire", best_seller="Candide"),
        Author(name="Jorge Luis Borges", best_seller="Labyrinths"),
        Author(name="Terry Pratchett", best_seller="Guards! Guards!"),
        Author(name="Rainer Maria Rilke", best_seller="Letters to a Young Poet"),
        Author(name="Arthur Miller", best_seller="The Crucible"),
        Author(name="Robert Frost", best_seller="The Road Not Taken"),
        Author(name="Gustave Flaubert", best_seller="Madame Bovary"),
        Author(name="J.D. Salinger", best_seller="Nine Stories"),
        Author(name="Sylvia Plath", best_seller="Ariel"),
        Author(name="Margaret Mitchell", best_seller="Gone with the Wind"),
        Author(name="James Baldwin", best_seller="Go Tell It on the Mountain"),
        Author(name="John Steinbeck", best_seller="East of Eden"),
        Author(name="Yukio Mishima",best_seller="The Sailor Who Fell from Grace with the Sea"),
        Author(name="Henry David Thoreau", best_seller="Walden"),
        Author(name="Michel de Montaigne", best_seller="Essays"),
        Author(name="James Joyce", best_seller="A Portrait of the Artist as a Young Man"),
        Author(name="Vladimir Nabokov", best_seller="Lolita"),
        Author(name="Mary Shelley", best_seller="Mathilda"),
        Author(name="Hermann Hesse", best_seller="Steppenwolf"),
        Author(name="Philip K. Dick", best_seller="Do Androids Dream of Electric Sheep?"),
        Author(name="Agatha Christie", best_seller="The Murder of Roger Ackroyd"),
        Author(name="Edgar Allan Poe", best_seller="Tales of Mystery and Imagination"),
        Author(name="Virginia Woolf", best_seller="To the Lighthouse"),
        Author(name="Margaret Atwood", best_seller="The Handmaid's Tale"),
        Author(name="Herman Melville", best_seller="Bartleby, the Scrivener"),
        Author(name="Gabriel Garcia Marquez", best_seller="Love in the Time of Cholera"),
        Author(name="Haruki Murakami", best_seller="Norwegian Wood"),
        Author(name="Charlotte Bronte", best_seller="Shirley"),
        Author(name="Edith Wharton", best_seller="The Age of Innocence"),
        Author(name="J.R.R. Tolkien", best_seller="The Hobbit"),
        Author(name="John Steinbeck", best_seller="Of Mice and Men"),
        Author(name="Fyodor Dostoevsky", best_seller="Crime and Punishment"),
        Author(name="Virginia Woolf", best_seller="A Room of One's Own"),
    ]

    genres = [
        Genre(name="Dystopian Fiction"),
        Genre(name="Romance"),
        Genre(name="Classic Literature"),
        Genre(name="Mystery"),
        Genre(name="Fantasy"),
        Genre(name="Historical Fiction"),
        Genre(name="Crime"),
        Genre(name="Magical Realism"),
        Genre(name="Historical Fiction"),
        Genre(name="Adventure"),
        Genre(name="Thriller"),
        Genre(name="Horror"),
        Genre(name="Young Adult"),
        Genre(name="Contemporary"),
        Genre(name="Biography"),
        Genre(name="Self-Help"),
        Genre(name="Humor"),
        Genre(name="Science"),
        Genre(name="Poetry"),
        Genre(name="Art"),
        Genre(name="Western"),
        Genre(name="Satire"),
        Genre(name="Children's"),
        Genre(name="Business"),
        Genre(name="Cooking"),
        Genre(name="Travel"),
        Genre(name="Science Fiction"),
        Genre(name="Fantasy"),
        Genre(name="Historical Nonfiction"),
        Genre(name="True Crime"),
        Genre(name="Music"),
        Genre(name="Drama"),
        Genre(name="Sports"),
        Genre(name="Psychology"),
        Genre(name="Paranormal"),
        Genre(name="Gardening"),
        Genre(name="Fashion"),
        Genre(name="Education"),
        Genre(name="Economics"),
        Genre(name="Anthology"),
        Genre(name="Film"),
        Genre(name="Journalism"),
        Genre(name="Health"),
        Genre(name="Religion"),
        Genre(name="Technology"),
        Genre(name="Nature"),
        Genre(name="Philosophy"),
        Genre(name="Crafts"),
        Genre(name="Supernatural"),
        Genre(name="Mythology"),
        Genre(name="Environment"),
        Genre(name="Architecture"),
        Genre(name="LGBTQ+"),
        Genre(name="Motivation"),
        Genre(name="Parenting"),
        Genre(name="Culinary"),
        Genre(name="Astrology"),
        Genre(name="DIY"),
        Genre(name="Folklore"),
        Genre(name="Business Ethics"),
        Genre(name="Time Travel"),
        Genre(name="Spy Fiction"),
        Genre(name="Medical"),
        Genre(name="Space Opera"),
        Genre(name="Apocalyptic"),
        Genre(name="Artificial Intelligence"),
        Genre(name="Financial Thriller"),
        Genre(name="Alternative History"),
        Genre(name="Experimental"),
        Genre(name="Cosmic Horror"),
        Genre(name="Steampunk"),
        Genre(name="Military History"),
        Genre(name="Romantic Comedy"),
        Genre(name="Psychological Thriller"),
        Genre(name="Space Exploration"),
        Genre(name="Surrealism"),
        Genre(name="Climate Fiction"),
        Genre(name="Historical Romance"),
        Genre(name="Sports Fiction"),
        Genre(name="Political Satire"),
        Genre(name="Urban Fantasy"),
        Genre(name="Post-Apocalyptic"),
        Genre(name="Parallel Universe"),
        Genre(name="Medical Thriller"),
        Genre(name="Survivalism"),
        Genre(name="Time Slip"),
        Genre(name="Epic Fantasy"),
        Genre(name="Conspiracy Thriller"),
        Genre(name="Nature Writing"),
        Genre(name="Legal Thriller"),
        Genre(name="Gothic Fiction"),
        Genre(name="Alternate Universe"),
        Genre(name="Regency Romance"),
        Genre(name="Cyberpunk"),
        Genre(name="Conspiracy Fiction"),
        Genre(name="Colonialism"),
        Genre(name="Aviation"),
        Genre(name="Business Biography"),
        Genre(name="Psychological Fiction"),
        Genre(name="Dark Fantasy"),
        Genre(name="Science Fantasy"),
        Genre(name="Philosophical Fiction"),
        Genre(name="Robots"),
        Genre(name="Medical Romance"),
        Genre(name="Economic Fiction"),
        Genre(name="Literary Criticism"),
        Genre(name="Historical Fantasy"),
        Genre(name="Philanthropy"),
        Genre(name="Futurism"),
    ]

    # Add instances to the session
    session.add_all(books + authors + genres)

    # Commit the changes
    session.commit()

    for i in range(109):
        books[i].author = authors[i]
        books[i].genre = genres[i]

    session.commit()
