"""Create table for Author

Revision ID: 18c1e9eaf258
Revises: be1f4bf5f872
Create Date: 2024-02-19 15:55:36.771290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c1e9eaf258'
down_revision: Union[str, None] = 'be1f4bf5f872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.create_table(
        'books',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('title', sa.String()),
        sa.Column('isbn', sa.Integer()),
        sa.Column('publication_date', sa.String()),
        sa.Column('description', sa.String()),
        sa.Column('publisher', sa.String()),
        sa.Column('language', sa.String()),
        sa.Column('pages_count', sa.Integer()),
        sa.Column('rating', sa.Integer()),
        sa.Column('genre_id', sa.Integer(), sa.ForeignKey('genres.id')),
        sa.Column('author_id', sa.Integer(), sa.ForeignKey('authors.id')),
        # Add other columns as needed
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.drop_table('books')
    # ### end Alembic commands ###
