"""Initial migration

Revision ID: 1af62a028e38
Revises: 
Create Date: 2024-02-19 14:01:26.185682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af62a028e38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'authors',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String()),
        sa.Column('best_seller', sa.String()),
    )

    op.create_table(
        'genres',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String()),
    )

    op.create_table(
        'books',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('title', sa.String()),
        sa.Column('isbn', sa.Integer()),
        sa.Column('publication_date', sa.String()),
        sa.Column('description', sa.String()),
        sa.Column('publisher', sa.String()),
        sa.Column('language', sa.String()),
        sa.Column('pages_count', sa.Integer()),
        sa.Column('rating', sa.Integer()),
        sa.Column('genre_id', sa.Integer(), sa.ForeignKey('genres.id')),
        sa.Column('author_id', sa.Integer(), sa.ForeignKey('authors.id')),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('genres')
    op.drop_table('authors')
    # ### end Alembic commands ###
